export const actionList = [
  {
    name: "Begin animation",
    type: "fixed",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Dévisser la cage du contre-couvercle",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Dévisser puis retirer la cage du contre-couvercle"],
    itemList: [],
  },
  {
    name: "Démontez la bague de serrage de la vis de dosage",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["49", "47", "48"],
  },
  {
    name: "Démontez la bague de serrage de la vis de dosage",
    type: "translateAndRotate",
    time: "2",
    refItemId: "49",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "-10", "720", "0", "0", "1"],
    itemList: ["49", "47", "48"],
  },
  {
    name: "Démontez la bague de serrage de la vis de dosage",
    type: "translate",
    time: "2",
    refItemId: "49",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "-100"],
    itemList: ["49", "47", "48"],
  },
  {
    name: "Démontez la bague de serrage de la vis de dosage",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Démontez la bague de serrage de la vis de dosage",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["49", "47", "48"],
  },
  {
    name: "Démontez la bague de serrage de l arbre de vis de dosage",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Démontez la bague de serrage de l arbre de vis de dosage"],
    itemList: [],
  },
  {
    name: "Démontez la bague de serrage de l arbre de vis de dosage",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["34"],
  },
  {
    name: "Démontez la bague de serrage de la vis de dosage",
    type: "translate",
    time: "2",
    refItemId: "34",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["-50", "0", "0"],
    itemList: ["34"],
  },
  {
    name: "Démontez la bague de serrage de la vis de dosage",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Démontez la bague de serrage de la vis de dosage",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["34"],
  },
  {
    name: "Retirez la poulie de la vis et son entretoise",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Retirez la poulie de la vis et son entretoise"],
    itemList: [],
  },
  {
    name: "Retirez la poulie de la vis et son entretoise",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["53", "52"],
  },
  {
    name: "Retirez la poulie de la vis et son entretoise",
    type: "translate",
    time: "2",
    refItemId: "53",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["-50", "0", "0"],
    itemList: ["53", "52"],
  },
  {
    name: "Retirez la poulie de la vis et son entretoise",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Retirez la poulie de la vis et son entretoise",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["52", "53"],
  },
  {
    name: "Démontez la bague de serrage des agitateurs",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Démontez la bague de serrage des agitateurs"],
    itemList: [],
  },
  {
    name: "Démontez la bague de serrage des agitateurs",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["54"],
  },
  {
    name: "Démontez la bague de serrage des agitateurs",
    type: "translate",
    time: "2",
    refItemId: "54",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "100"],
    itemList: ["54"],
  },
  {
    name: "Démontez la bague de serrage des agitateurs",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Démontez la bague de serrage des agitateurs",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["54"],
  },
  {
    name: "Retirez la poulie des agitateurs et son entretoise",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Retirez la poulie des agitateurs et son entretoise"],
    itemList: [],
  },
  {
    name: "Retirez la poulie des agitateurs et son entretoise",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["45", "50"],
  },
  {
    name: "Retirez la poulie des agitateurs et son entretoise",
    type: "translate",
    time: "2",
    refItemId: "45",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "100"],
    itemList: ["45", "50"],
  },
  {
    name: "Retirez la poulie des agitateurs et son entretoise",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Retirez la poulie des agitateurs et son entretoise",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["45", "50"],
  },
  {
    name: "Retirez l arbre de commande de la vis",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Retirez l arbre de commande de la vis"],
    itemList: [],
  },
  {
    name: "Retirez l arbre de commande de la vis",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["51", "46"],
  },
  {
    name: "Retirez l arbre de commande de la vis",
    type: "translate",
    time: "2",
    refItemId: "51",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "-100"],
    itemList: ["51", "46"],
  },
  {
    name: "Retirez l arbre de commande de la vis",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Retirez l arbre de commande de la vis",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["51", "46"],
  },
  {
    name: "Retirez la cage à roulements et ses roulements",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Retirez la cage à roulements et ses roulements par le bas"],
    itemList: [],
  },
  {
    name: "Retirez la cage à roulements et ses roulements",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: [
      "37",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "38",
    ],
  },
  {
    name: "Retirez la cage à roulements et ses roulements",
    type: "translate",
    time: "2",
    refItemId: "37",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "-150"],
    itemList: [
      "37",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "38",
    ],
  },
  {
    name: "Retirez la cage à roulements et ses roulements",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Retirez la cage à roulements et ses roulements",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: [
      "37",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "38",
    ],
  },
  {
    name: "Retirez le roulement Ø30 Ø47 supérieur",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Retirez le roulement Ø30 Ø47 supérieur"],
    itemList: [],
  },
  {
    name: "Retirez le roulement Ø30 Ø47 supérieur",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["0", "1", "2", "3", "4"],
  },
  {
    name: "Retirez le roulement Ø30 Ø47 supérieur",
    type: "translate",
    time: "2",
    refItemId: "1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["30", "0", "0"],
    itemList: ["0", "1", "2", "3", "4"],
  },
  {
    name: "Retirez le roulement Ø30 Ø47 supérieur",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Retirez le roulement Ø30 Ø47 supérieur",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["0", "1", "2", "3", "4"],
  },
  {
    name: "Retirez l entretoise des roulements d agitateurs",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Retirez l entretoise des roulements d agitateurs"],
    itemList: [],
  },
  {
    name: "Retirez l entretoise des roulements d agitateurs",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["36"],
  },
  {
    name: "Retirez l entretoise des roulements d agitateurs",
    type: "translate",
    time: "2",
    refItemId: "36",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "75"],
    itemList: ["36"],
  },
  {
    name: "Retirez l entretoise des roulements d agitateurs",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Retirez l entretoise des roulements d agitateurs",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["36"],
  },
  {
    name: "Dévissez les 4 vis H M4 du couvercle de cage ",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Dévissez les 4 vis H M4 du couvercle de cage "],
    itemList: [],
  },
  {
    name: "Dévissez les 4 vis H M4 du couvercle de cage ",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["40", "42", "41", "43"],
  },
  {
    name: "Dévissez les 4 vis H M4 du couvercle de cage ",
    type: "translateAndRotate",
    time: "2",
    refItemId: "40",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "50", "720", "0", "0", "-1"],
    itemList: ["40"],
  },
  {
    name: "Dévissez les 4 vis H M4 du couvercle de cage ",
    type: "translateAndRotate",
    time: "2",
    refItemId: "42",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "50", "720", "0", "0", "-1"],
    itemList: ["42"],
  },
  {
    name: "Dévissez les 4 vis H M4 du couvercle de cage ",
    type: "translateAndRotate",
    time: "2",
    refItemId: "41",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "50", "720", "0", "0", "-1"],
    itemList: ["41"],
  },
  {
    name: "Dévissez les 4 vis H M4 du couvercle de cage ",
    type: "translateAndRotate",
    time: "2",
    refItemId: "43",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "50", "720", "0", "0", "-1"],
    itemList: ["43"],
  },
  {
    name: "Dévissez les 4 vis H M4 du couvercle de cage ",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Dévissez les 4 vis H M4 du couvercle de cage ",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["40", "42", "41", "43"],
  },
  {
    name: "Retirez le couvercle de cage",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Retirez le couvercle de cage"],
    itemList: [],
  },
  {
    name: "Retirez le couvercle de cage",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["39", "44"],
  },
  {
    name: "Retirez le couvercle de cage",
    type: "translate",
    time: "2",
    refItemId: "39",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["0", "0", "-50"],
    itemList: ["39", "44"],
  },
  {
    name: "Retirez le couvercle de cage",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Retirez le couvercle de cage",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["39", "44"],
  },
  {
    name: "Retirez le roulement Ø30 Ø47 inférieur",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Retirez le roulement Ø30 Ø47 inférieur"],
    itemList: [],
  },
  {
    name: "Retirez le roulement Ø30 Ø47 inférieur",
    type: "color",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["255", "0", "0", "0"],
    itemList: ["6", "5", "7", "8", "9"],
  },
  {
    name: "Retirez le roulement Ø30 Ø47 inférieur",
    type: "translate",
    time: "2",
    refItemId: "8",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: ["-50", "0", "0"],
    itemList: ["6", "5", "7", "8", "9"],
  },
  {
    name: "Retirez le roulement Ø30 Ø47 inférieur",
    type: "break",
    time: "2",
    refItemId: "-1",
    isBlocker: "true",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
  {
    name: "Retirez le roulement Ø30 Ø47 inférieur",
    type: "hide",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["true"],
    itemList: ["6", "5", "7", "8", "9"],
  },
  {
    name: "Le démontage est entièrement réalisé",
    type: "text",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: ["Le démontage est entièrement réalisé"],
    itemList: [],
  },
  {
    name: "End animation",
    type: "fixed",
    time: "0",
    refItemId: "-1",
    isBlocker: "false",
    optionHidden: "default",
    uid: "",
    argList: [],
    itemList: [],
  },
];
