export const exampleAnimation = {
  version: "2.0",
  actionList: [
    {
      name: "hide",
      type: "hide",
      time: "0",
      refItemId: "1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["true"],
      itemList: ["1"],
    },
    {
      name: "Display Text",
      type: "text",
      time: "2",
      refItemId: "1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["lorem Ipsum"],
      itemList: ["1"],
    },
    {
      name: "Scale 0",
      type: "scale",
      time: "2",
      refItemId: "0",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["100", "100", "100"],
      itemList: ["0"],
    },
    {
      name: "Color",
      type: "color",
      time: "0",
      refItemId: "0",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["0", "0", "0"],
      itemList: ["100", "100", "100"],
    },
    {
      name: "ROTATE 1 -X",
      type: "rotate",
      time: "2",
      refItemId: "1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["-202", "0", "0"],
      itemList: ["1"],
    },
    {
      name: "TRANSLATE and ROTATE 0 -X",
      type: "translateAndRotate",
      time: "5",
      refItemId: "141",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["-202", "0", "0", "0", "200", "0"],
      itemList: ["141"],
    },
    {
      name: "translate 1 -X",
      type: "translate",
      time: "1",
      refItemId: "1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["-202", "0", "0"],
      itemList: ["1"],
    },
    {
      name: "translate 1 X",
      type: "translate",
      time: "1",
      refItemId: "1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["202", "0", "0"],
      itemList: ["1"],
    },
    {
      name: "translate 0 X",
      type: "translate",
      time: "1",
      refItemId: "0",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["+202", "0", "0"],
      itemList: ["1"],
    },
    {
      name: "translate 0 -X",
      type: "translate",
      time: "1",
      refItemId: "0",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["-202", "0", "0"],
      itemList: ["1"],
    },
    {
      name: "translate 0 Z",
      type: "translate",
      time: "1",
      refItemId: "0",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["0", "0", "200"],
      itemList: ["1"],
    },
    {
      name: "translate 0 -Z",
      type: "translate",
      time: "1",
      refItemId: "0",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["0", "0", "-200"],
      itemList: ["1"],
    },
    {
      name: "Show",
      type: "hide",
      time: "0",
      refItemId: "1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["false"],
      itemList: ["1"],
    },
  ],
};

export const exampleAnimation2 = {
  version: "2.0",
  actionList: [
    {
      name: "translate",
      type: "translate",
      time: "1",
      refItemId: "1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["-202", "0", "0"],
      itemList: ["1"],
    },
    {
      name: "Begin animation",
      type: "fixed",
      time: "0",
      refItemId: "-1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: [],
      itemList: [],
    },
    {
      name: "1er etape",
      type: "hide",
      time: "0",
      refItemId: "-1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: ["false"],
      itemList: ["141"],
    },
    {
      name: "déplacer",
      type: "translate",
      time: "1",
      refItemId: "55",
      isBlocker: "true",
      optionHidden: "default",
      uid: "",
      argList: ["1", "-100", "0"],
      itemList: ["55"],
    },
    {
      name: "zdfvc",
      type: "translate",
      time: "-1",
      refItemId: "55",
      isBlocker: "true",
      optionHidden: "default",
      uid: "",
      argList: ["-202", "0", "0"],
      itemList: ["55"],
    },
    {
      name: "New Step",
      type: "noAction",
      time: "0",
      refItemId: "-1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: [],
      itemList: [],
    },
    {
      name: "New Step",
      type: "noAction",
      time: "0",
      refItemId: "-1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: [],
      itemList: [],
    },
    {
      name: "End animation",
      type: "fixed",
      time: "0",
      refItemId: "-1",
      isBlocker: "false",
      optionHidden: "default",
      uid: "",
      argList: [],
      itemList: [],
    },
  ],
};
